// Constants
export const FETCHING_FILE = 'FETCHING_FILE'
export const FILE_PARSE_ERROR = 'FILE_PARSE_ERROR'
export const STORE_FILE_DATA = 'STORE_FILE_DATA'
export const UPDATE_SELECTION_INDICES = 'UPDATE_SELECTION_INDICES'
